steps:
  # This step builds the container image
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/benjamin-stedi:latest"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args: 
      - "push"
      - "gcr.io/$PROJECT_ID/benjamin-stedi:latest"
  - name: gcr.io/cloud-builders/gke-deploy
    id: Deploy
    args:
     - run
     - --filename=manifest.yaml
     - --image=gcr.io/$PROJECT_ID/benjamin-stedi:latest
     - --location=us-west1-b
     - --cluster=cluster-2
  - name: "gcr.io/cloud-builders/docker"
    id: Test
    args: 
    - "run"
    - "gcr.io/$PROJECT_ID/benjamin-stedi:latest"

# testing 2