#© 2021 Sean Murdock

apiVersion: apps/v1
kind: Deployment
metadata:
  name: benjamin-stedi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benjamin-stedi
  template:
    metadata:
      labels:
        app: benjamin-stedi
    spec:
      containers:
        - name: benjamin-stedi
          image: gcr.io/power-glove/stedi-benjamin:latest
          command: ["npm"]
          args: ["run", "start"]
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: ".125"
              memory: "500Mi"
            requests:
              cpu: ".1"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3